IF EXISTS(SELECT 1 FROM sys.databases WHERE name = 'school')
BEGIN
  USE school;
END
GO

create table teacher(
  id        uniqueidentifier default newid()  not null,
  name      varchar(250)                     not null
)
go

insert into teacher(name) values('John')
insert into teacher(name) values('Mary')
insert into teacher(name) values('Peter')
insert into teacher(name) values('Paul')
insert into teacher(name) values('James')
insert into teacher(name) values('Jude')
insert into teacher(name) values('Simon')
insert into teacher(name) values('Thomas')
insert into teacher(name) values('Andrew')
insert into teacher(name) values('Philip')
insert into teacher(name) values('Bartholomew')
insert into teacher(name) values('Matthew')
insert into teacher(name) values('Thaddaeus')
insert into teacher(name) values('Matthias')
insert into teacher(name) values('Mark')
insert into teacher(name) values('Luke')
insert into teacher(name) values('Timothy')
insert into teacher(name) values('Titus')
insert into teacher(name) values('Philemon')
insert into teacher(name) values('Barnabas')
insert into teacher(name) values('Silas')
insert into teacher(name) values('Apollos')
insert into teacher(name) values('Aristarchus')
insert into teacher(name) values('Epaphras')
insert into teacher(name) values('Epaphroditus')
insert into teacher(name) values('James')
insert into teacher(name) values('John')
insert into teacher(name) values('Judas')
insert into teacher(name) values('Luke')
insert into teacher(name) values('Mark')
insert into teacher(name) values('Matthew')
insert into teacher(name) values('Paul')
insert into teacher(name) values('Peter')
insert into teacher(name) values('Philip')
insert into teacher(name) values('Simon')
insert into teacher(name) values('Thomas')
insert into teacher(name) values('Timothy')
insert into teacher(name) values('Titus')
insert into teacher(name) values('Barnabas')
insert into teacher(name) values('Silas')
insert into teacher(name) values('Apollos')
insert into teacher(name) values('Aristarchus')
insert into teacher(name) values('Epaphras')
insert into teacher(name) values('Epaphroditus')
insert into teacher(name) values('James')
insert into teacher(name) values('John')
insert into teacher(name) values('Judas')
insert into teacher(name) values('Luke')
insert into teacher(name) values('Mark')
insert into teacher(name) values('Matthew')
insert into teacher(name) values('Paul')
insert into teacher(name) values('Peter')
insert into teacher(name) values('Philip')
insert into teacher(name) values('Simon')
insert into teacher(name) values('Thomas')
insert into teacher(name) values('Timothy')
