name: Test

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

env:
  DOTNET_VERSION: '8.0.101'
  WEBAPP_URL: http://localhost:6900

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Run MSSQL Container
      - name: Run MSSQL Container
        run: |
          docker compose up -d

      # Test database connection
      - name: Test database connection
        run: |
          set +e
          output=$(docker exec database /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P P@ssw0rd -i /test/test.sql 2>&1)
          is_up=$?
          while [ $is_up -ne 0 ] || [[ ! $output =~ "hay 56 registros" ]] ; do
            output=$(docker exec database /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P P@ssw0rd -i /test/test.sql 2>&1)
            is_up=$?
            echo "$is_up: $output"
            sleep 5 
          done
          set -e

      # Setup .NET Core SDK
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      # Build and publish project
      - name: Build and publish project
        run: |
          dotnet publish --configuration Release --output ./output SchoolAPI/SchoolAPI.csproj

      # Run project in background
      - name: Run project
        run: dotnet ./output/SchoolAPI.dll &
        env:
          ASPNETCORE_ENVIRONMENT: Development
          ASPNETCORE_URLS: ${{ env.WEBAPP_URL }}

      # Wait for project to start
      - name: Wait for project to start
        run: sleep 5

      # Validate project is running
      - name: Validate project is running
        run: |
          output=$(curl -s ${{ env.WEBAPP_URL }}/hello 2>&1)
          echo "$output"