name: Test

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Run MSSQL Container
      - name: Run MSSQL Container
        run: |
          docker run -e "ACCEPT_EULA=Y" -e "SA_PASSWORD=P@ssw0rd" -v "./.devcontainer/mssql/:/scripts/" -p 1433:1433 --name mssql -d mcr.microsoft.com/mssql/server:2022-latest /bin/bash init_db.sh

      # Wait for MSSQL to start
      - name: Wait for MSSQL to start
        run: |
          sleep 10

      # Test database connection
      - name: Test database connection
        run: |
          docker exec mssql /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P P@ssw0rd -Q "select count(id) from school.teacher"

      # - uses: actions/checkout@v4
      #   with:
      #     fetch-depth: 0
      # - uses: actions/setup-node@v4
      #   with:
      #     node-version: 20
      # - name: Run server
      #   run: |
      #     node server.js &
      #     sleep 5
      # - name: Run tests
      #   run: |
      #     curl localhost:6000