name: Test

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

env:
  DOTNET_VERSION: '8.0.101'
  WEBAPP_URL: localhost:6900
  DATABASE_NAME: school
  DATABASE_PASSWORD: P@ssw0rd

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Start MSSQL Container and setup database
        run: |
          docker compose up -d
          set +e
          output=$(docker exec database /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P ${{ env.DATABASE_PASSWORD }} -i /test/test.sql 2>&1)
          is_up=$?
          while [ $is_up -ne 0 ] || [[ ! $output =~ "hay 15 registros" ]] ; do
            output=$(docker exec database /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P ${{ env.DATABASE_PASSWORD }} -i /test/test.sql 2>&1)
            is_up=$?
            echo "$is_up: $output"
            sleep 5 
          done
          set -e

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Build and start WebApp
        run: |
          dotnet publish --configuration Release --output ./output SchoolAPI/SchoolAPI.csproj
          dotnet ./output/SchoolAPI.dll &
          set +e
          output=$(curl -s -H "Content-Type: application/json" -d '{"query":"{ ping }"}' http://${{ env.WEBAPP_URL }}/graphql 2>&1)
          is_up=$?
          echo $output
          while [[ ! $output =~ "pong" ]] ; do
            output=$(curl -s -H "Content-Type: application/json" -d '{"query":"{ ping }"}' http://${{ env.WEBAPP_URL }}/graphql 2>&1)
            is_up=$?
            echo "$is_up: $output"
            sleep 5
          done
          set -e
        env:
          ASPNETCORE_ENVIRONMENT: Development
          ASPNETCORE_URLS: http://${{ env.WEBAPP_URL }}
          ConnectionStrings__DefaultConnection: "Initial Catalog=${{ env.DATABASE_NAME }}; Data Source=localhost; user id=sa;password=${{ env.DATABASE_PASSWORD }};Authentication=SqlPassword;TrustServerCertificate=True;MultipleActiveResultSets=True;"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Run websocket test
        run: |
          cd SchoolAPI.Test.WS
          npm install
          npm run test
        env:
          WEBAPP_URL: ${{ env.WEBAPP_URL }}
