name: Test

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Run MSSQL Container
      - name: Run MSSQL Container
        run: |
          docker compose up -d

      # Wait for MSSQL to start
      # - name: Wait for MSSQL to start
      #   run: |
      #     sleep 15

      # 
      # - name: Get container name
      #   run: |
      #     docker ps -a

      # Test database connection
      - name: Test database connection
        run: |
          set +e
          output=$(docker exec database /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P P@ssw0rd -i /test/test.sql 2>&1)
          is_up=$?
          echo "$is_up: $output"
          while [ $is_up -ne 0 && ! $output =~ "56" ] ; do 
            output=$(docker exec database /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P P@ssw0rd -i /test/test.sql 2>&1)
            is_up=$?
            echo "$is_up: $output"
            sleep 5 
          done
          echo $output"
          set -e

      # - uses: actions/setup-node@v4
      #   with:
      #     node-version: 20
      # - name: Run server
      #   run: |
      #     node server.js &
      #     sleep 5
      # - name: Run tests
      #   run: |
      #     curl localhost:6000